tap "d12frosted/emacs-plus"
tap "coursier/formulas"

brew "d12frosted/emacs-plus/emacs-plus@30"
brew "openjdk@17"
brew "openjdk@21"
brew "node@24"
brew "coursier/formulas/coursier"
brew "cmake"
brew "fd"
brew "gradle"
brew "groovy"
brew "libvterm"
brew "ripgrep"
brew "ruff"
brew "shellcheck"
brew "shfmt"

cask "font-symbols-only-nerd-font"
