;;; gm-cursor-dark-theme.el --- Cursor Dark-inspired theme -*- lexical-binding: t; -*-

(deftheme gm-cursor-dark "An original dark theme based on the local Cursor palette.")

(let ((bg "#181818") (panel "#141414") (line "#262626")
      (fg "#F0F0F0") (muted "#A0A0A0") (dim "#666666")
      (border "#242424") (selection "#404040")
      (pink "#E394DC") (teal "#82D2CE") (orange "#EFB080")
      (blue "#87C3FF") (purple "#AAA0FA") (gold "#EBC88D")
      (green "#70B489") (red "#E34671") (yellow "#F8C762")
      (cyan "#88C0D0"))
  (custom-theme-set-faces
   'gm-cursor-dark
   `(default ((t (:family "Menlo" :height 120 :background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:background ,bg :foreground ,dim))))
   `(region ((t (:background ,selection :extend t))))
   `(highlight ((t (:background ,line))))
   `(hl-line ((t (:background ,line :extend t))))
   `(shadow ((t (:foreground ,dim))))
   `(link ((t (:foreground ,blue :underline t))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight semi-bold))))
   `(line-number ((t (:foreground ,dim :background ,bg))))
   `(line-number-current-line ((t (:foreground ,fg :background ,line :weight bold))))
   `(vertical-border ((t (:foreground ,border))))
   `(window-divider ((t (:foreground ,border))))
   `(mode-line ((t (:background ,panel :foreground ,fg :box (:line-width 1 :color ,border)))))
   `(mode-line-inactive ((t (:background ,panel :foreground ,dim :box (:line-width 1 :color ,border)))))
   `(tab-line ((t (:background ,panel :foreground ,muted :height 0.95))))
   `(tab-line-tab ((t (:background ,bg :foreground ,fg :box (:line-width 1 :color ,border)))))
   `(tab-line-tab-current ((t (:background ,bg :foreground ,fg :weight bold :overline ,blue))))
   `(tab-line-tab-inactive ((t (:background ,panel :foreground ,dim))))
   `(font-lock-builtin-face ((t (:foreground ,cyan))))
   `(font-lock-comment-face ((t (:foreground ,dim :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,dim))))
   `(font-lock-constant-face ((t (:foreground ,gold))))
   `(font-lock-doc-face ((t (:foreground ,muted))))
   `(font-lock-function-call-face ((t (:foreground ,orange))))
   `(font-lock-function-name-face ((t (:foreground ,orange))))
   `(font-lock-keyword-face ((t (:foreground ,teal :weight semi-bold))))
   `(font-lock-number-face ((t (:foreground ,gold))))
   `(font-lock-preprocessor-face ((t (:foreground ,green))))
   `(font-lock-property-name-face ((t (:foreground ,purple))))
   `(font-lock-string-face ((t (:foreground ,pink))))
   `(font-lock-type-face ((t (:foreground ,orange))))
   `(font-lock-variable-name-face ((t (:foreground ,blue))))
   `(font-lock-warning-face ((t (:foreground ,yellow :weight bold))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(flycheck-error ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flycheck-info ((t (:underline (:style wave :color ,blue)))))
   `(corfu-default ((t (:background ,panel :foreground ,fg))))
   `(corfu-current ((t (:background ,selection :foreground ,fg))))
   `(vertico-current ((t (:background ,selection :foreground ,fg :extend t))))
   `(company-tooltip ((t (:background ,panel :foreground ,fg))))
   `(company-tooltip-selection ((t (:background ,selection :foreground ,fg))))
   `(treemacs-root-face ((t (:foreground ,fg :weight bold :height 1.05))))
   `(treemacs-directory-face ((t (:foreground ,muted))))
   `(treemacs-file-face ((t (:foreground ,muted))))
   `(treemacs-git-added-face ((t (:foreground ,green))))
   `(treemacs-git-modified-face ((t (:foreground ,yellow))))
   `(treemacs-git-conflict-face ((t (:foreground ,red))))
   `(diff-added ((t (:background ,panel :foreground ,green))))
   `(diff-removed ((t (:background ,panel :foreground ,red))))
   `(diff-changed ((t (:background ,panel :foreground ,yellow))))
   `(magit-section-heading ((t (:foreground ,blue :weight bold))))
   `(magit-branch-local ((t (:foreground ,purple))))
   `(magit-branch-remote ((t (:foreground ,green))))
   `(whitespace-trailing ((t (:background ,red))))))

(provide-theme 'gm-cursor-dark)
;;; gm-cursor-dark-theme.el ends here
